version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: codeflix_catalog_frontend
    volumes:
      - ./frontend:/home/node/app
      - frontend_node_modules:/home/node/app/node_modules
    command: npm run dev
    networks:
      - catalog-net
    ports:
      - 3001:3000

  catalog-api:
    build: ./api
    container_name: codeflix_catalog_api
    tty: true
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/keyfile.json
      - WAIT_FOR_DB_URL=db:5432
    env_file:
      - ./api/.env
    volumes:
      - ./api:/home/node/app
      - api_node_modules:/home/node/app/node_modules
      - "${GCLOUD_KEYFILE}:/tmp/keys/keyfile.json:ro"
    command: npm run start:debug
    networks:
      - catalog-net
    ports:
      - 3000:8080
    depends_on:
      - db

  db:
    image: postgres
    container_name: codeflix_catalog_db
    environment:
      - POSTGRES_DB=catalog
      - POSTGRES_USER=catalog
      - POSTGRES_PASSWORD=catalog
    restart: always
    tty: true
    ports:
      - 5432:5432
    networks:
      - catalog-net
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  catalog-net:
    driver: bridge

volumes:
  pgdata:
  api_node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./api/node_modules
  frontend_node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./frontend/node_modules
