version: '3.8'

services:
  catalog:
    build: .
    container_name: codeflix_catalog_api
    tty: true
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/keyfile.json
      - WAIT_FOR_DB_URL=db:5432
    env_file:
      - .env
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
      - "${HOST_GCLOUD_KEYFILE}:/tmp/keys/keyfile.json:ro"
    networks:
      - catalog-net
    ports:
      - 3000:8080
    depends_on:
      - db

  db:
    image: postgres
    container_name: codeflix_catalog_db
    environment:
      - POSTGRES_DB=catalog
      - POSTGRES_USER=catalog
      - POSTGRES_PASSWORD=catalog
    restart: always
    tty: true
    ports:
      - 5432:5432
    networks:
      - catalog-net
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  catalog-net:
    driver: bridge

volumes:
  node_modules:
  pgdata:
